### ISSUE TITLE
Question about citing this code

### ISSUE THREAD

**Issue by AlexandrosKoukras** [dstansby/solarsynoptic#6]
Hello,

How I should cite this code, if results of these programs (synoptic maps) are used for a scientific publication?

Thank you.

**Comment by dstansby** [comment]
Hello, first thanks for asking! I guess it depends what you want to acheive by citing. If it's to acknowledge the work that I did to wrtie these cdoes, then a short sentence in the acknowledgement section would be nice. If it's to point people to the code for reproduciblity, I can create a release and archive it on zenodo to give it a DOI you can cite?

**Comment by AlexandrosKoukras** [comment]
It is mostly to acknowledge your work.
If you have a preference for the sentence in the acknowledgment section please let me know.

**Comment by dstansby** [comment]
I don't have a preference - feel free to choose your own sentence 😄
